---
format:
  html:
    include-in-header:
      - text: |
         <link rel="icon" type="image/png" href="../assets/cover.jpg">
---

# 1. Introduction {.unnumbered}

::: paratext
In the last decades, addressing the issue of climate change has become increasingly urgent. Governments worldwide have embarked on ambitious plans to lower carbon dioxide emissions and reduce energy consumption due to this heightened awareness. The European Union has established a long-term strategy to become a climate-neutral economy with net-zero greenhouse gas emissions. With this plan, the EU aims to establish a crucial stepping stone for the world to achieve the goal of the Paris Agreement by keeping global warming below 2 degrees Celsius. This goal emphasized the urgent need for substantial economic change to reduce carbon dioxide emissions, particularly in high-emissions sectors. Among those sectors is the building industry, which is estimated to be responsible for 40% of global carbon dioxide emissions [@carlin_40_2022]. About 70% of these emissions are generated by building operations, while construction activities contribute the remaining 30% [@carlin_40_2022]. Regarding the European Union, the European Environment Agency [-@european_enviroment_agency_greenhouse_2023] published a report stating that the building sector is responsible for about 35% of energy-related emissions in the European Union for the year 2021.These emissions are primarily connected to activities like the combustion of fossil fuels within buildings, such as oil and gas boilers for heating, alongside electricity consumption for lighting, water heating, and cooling systems. In 2002, the EU introduced the Energy Performance of Buildings Directive (EPBD) with the main objective of promoting energy efficiency [@ec_eu_2002]. The European Union acknowledged the importance of a new policy instrument to tackle the emissions from the building

EPBD introduced the energy performance certificates (EPC) to tackle both the information failures, i.e. the information gap on the energy efficiency of properties that exists between property owners and prospective buyers, as well as the behavioral failure, such as decision-making heuristics and biases. This initiative aims to provide property buyers with accurate, direct, and cost-free information to ensure they can make well-informed decisions that would otherwise be contained by lack of transparency. Additionally, the information that the EPC reports provide can serve as a motivator for both owners and builders to invest in energy-efficient measures since it can be hypothesized that higher property prices and rents can result from a building's improved energy performance. The Directive did not, however, compel property owners to publicly reveal the energy label, i.e., their property's energy performance, in an advert. However, a recast of the EU Directive on the energy performance of buildings was set in place in 2010. This recast imposed on Member States to make it a requirement that property owners include the energy performance indicator, i.e. the energy performance rating ranging from A to G, in any commercial media real estate advertisement [@eu_eu_2010]. Interestingly, between 2005 and 2021, total carbon dioxide emissions from the EU building sector dropped by 31% [@european_enviroment_agency_greenhouse_2023]

Since 1997, it has been mandatory in Denmark to have an energy certification. This makes Denmark one of the first countries in the EU to implement an EPC scheme, which includes benchmarking, an energy label, and an energy performance rating in the building sector. Interestingly, even though Denmark became one of the first to implement the system, they did not observe an impact on the real estate market until 2011, i.e., one year after the recast of the EPBD [@jensen_market_2016]. The 2010 recast sparked many research studies to investigate the relationship between the energy performance of properties and property prices. The majority of the studies that investigate the EU housing market focus on the energy label. Other studies focus either on estimated or measured energy consumption. The results of these studies, however, have been mixed. Some studies identify significant price premiums associated with high energy performance labels or low energy consumption, whereas others observe no premium at all. Overall, the majority of studies identify significant price premiums, indicating a general trend toward the valuation of energy-efficient properties [@cespedes-lopez_meta-analysis_2019]. Concerning the Danish housing market, there is only a small amount of existing literature on the subject where the latest research that was found was conducted in the year 2016 [see @christensen_energy_2014; @jensen_market_2016; and @naess-schmidt_homes_2015]. Furthermore, only a limited number of studies have taken into account additional information stated in the EPC reports, such as the renovation recommendations, renovations cost, and investment cost stated in the reports or the potential energy label a property can obtain from implementing recommended renovations.

This study investigates the relationship between energy performance and property prices by accounting for additional information taken from the reports. A hedonic model is applied to a unique data set of properties in Denmark from the years 2010 to 2023. Information is extracted using regular expressions, OCR, and NLP text classification techniques from over 776,106 EPC reports and then combined with scraped property characteristics and transaction data consisting of over 2.2 million observations, obtained from the website [boliga.dk](https://www.boliga.dk/). Once all data is merged and cleaned, we obtain a final sample consisting of over 728,794 observations.

With this unique dataset, the contributions of this thesis are threefold. Firstly, it is the first paper to account for all residential property types in Denmark. To the best of our knowledge, all studies that investigate the Danish housing market have only focused on detached houses. Secondly, besides the energy label and energy consumption, we incorporate additional information from the EPC reports related to renovation potentials toward energy efficiency. The Idea here is that if consumers pay attention to the information in the EPC reports and are willing to pay a price premium for energy-efficient property, hence a discount for non-energy efficient property, then that premium/discount might vary depending on the renovation potential and the energy efficiency that the property can achieve from it. This might play a significant role in non-energy efficient properties. Finally, we measure the effect of tighter policy implementation for the Danish housing market on property renovations. The Danish authorities implemented tighter building regulations on January 1, 2018, which set minimum energy performance requirements for all new buildings and minimum energy efficiency requirements for renovations of existing buildings.

The thesis is structured as follows: [Chapter 2: EPBD and the Danish EPC scheme](epbd_and_danish_EPC_scheme.qmd) introduces the implementation of the Energy Performance Certificates in Denmark and the structure of the reports. Subsequently, [Chapter 3: Literature Review](literature_review.qmd) looks into the literature related to this paper. [Chapter 4: Data](data/data_housing.qmd) chapter gives a detailed description of the data and how it was obtained. [Chapter 5: Empirical Strategy](empirical_strategy/empirical_strategy_EstimationStrategy.qmd) outlines the theory of the hedonic model and the empirical strategy utilized in this paper. Finally, in the [Chapter 6: Results](results.qmd), we present the results.
:::
